const Gallerydata = [
    {
      id: 1,
      category: 'bhawan',
      imgSrc: '/images/gallery1.jpeg',
      alt: 'bhawan_3',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 2,
      category: 'event',
      imgSrc: '/images/gallery2.jpg',
      alt: 'event_2',
      title: 'Events',
      description: 'Events',
      lightboxTitle: 'Events in Bhawan',
    },
    {
      id: 3,
      category: 'sports',
      imgSrc: '/images/gallery3.jpeg',
      alt: 'sports_10',
      title: 'Sports',
      description: 'Sports',
      lightboxTitle: 'Sports in IIT Roorkee',
    },
    {
      id: 4,
      category: 'event',
      imgSrc: '/images/gallery4.jpg',
      alt: 'event_2',
      title: 'Events',
      description: 'Events',
      lightboxTitle: 'Events in Bhawan',
    },
    {
      id: 5,
      category: 'bhawan',
      imgSrc: '/images/gallery5.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 1,
      category: 'bhawan',
      imgSrc: '/images/gallery1.jpeg',
      alt: 'bhawan_3',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 2,
      category: 'event',
      imgSrc: '/images/gallery2.jpg',
      alt: 'event_2',
      title: 'Events',
      description: 'Events',
      lightboxTitle: 'Events in Bhawan',
    },
    {
      id: 6,
      category: 'bhawan',
      imgSrc: '/images/gallery6.webp',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 7,
      category: 'bhawan',
      imgSrc: '/images/gallery7.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 8,
      category: 'bhawan',
      imgSrc: '/images/gallery8.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 9,
      category: 'bhawan',
      imgSrc: '/images/gallery9.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 7,
      category: 'bhawan',
      imgSrc: '/images/gallery7.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 8,
      category: 'bhawan',
      imgSrc: '/images/gallery8.jpeg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    {
      id: 10,
      category: 'bhawan',
      imgSrc: '/images/gallery10.jpg',
      alt: 'bhawan_1.jpg',
      title: 'Bhawan',
      description: 'Bhawan',
      lightboxTitle: 'Azad Bhawan',
    },
    // Add more gallery items here
  ];
  
  export default Gallerydata;
  